CREATE TABLE IF NOT EXISTS assets
(
    id             INTEGER PRIMARY KEY NOT NULL,
    ticker         TEXT UNIQUE NOT NULL,

    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
