CREATE TABLE IF NOT EXISTS users
(
    id             INTEGER PRIMARY KEY NOT NULL,
    name           TEXT UNIQUE NOT NULL,

    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO users (name) VALUES("Default");
